name: Build GACL

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * *" # 2:00 AM PST (UTC-8)

jobs:
  build:
    name: Build (matrix)
    runs-on: windows-latest
    timeout-minutes: 180
    permissions:
      checks: write
      contents: read

    strategy:
      fail-fast: false
      matrix:
        configuration: [Debug, Release]
        platform: [x64]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1
          lfs: false
          
      - name: Restore NuGet packages
        run: |
          nuget restore gacl.sln `
            -ConfigFile nuget.config `
            -PackagesDirectory packages `
            -Source "https://api.nuget.org/v3/index.json" `

      - name: Setup MSBuild (VS 2022)
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: '17.0'

      - name: Setup CLER
        shell: pwsh
        run: |
          Tools\scripts\setupCLER.ps1

      - name: Build gacl.sln
        run: |
          msbuild gacl.sln `
            /t:Rebuild `
            /p:Configuration=${{ matrix.configuration }} `
            /p:Platform=${{ matrix.platform }} `
            /p:OutDir=${{ github.workspace }}\out\${{ matrix.configuration }}\${{ matrix.platform }}\bin\
      
      - name: Run native tests
        shell: pwsh
        run: |
          $binDir = "${{ github.workspace }}\out\${{ matrix.configuration }}\${{ matrix.platform }}\bin"
          $testBins = Get-ChildItem -Path $binDir `
            -Filter "*tests.exe" -Recurse
          foreach ($test in $testBins) {
            Push-Location $binDir
            & $test.FullName `
              --gtest_output=xml:"${{ github.workspace }}\TestResults\$($test.BaseName).xml"
            Pop-Location
          }

      - name: Publish test results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Test Results (${{ matrix.configuration }}-${{ matrix.platform }})
          path: TestResults/*.xml
          reporter: java-junit

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gacl-${{ matrix.configuration }}-${{ matrix.platform }}
          path: out
