name: Test GACL

on:
  workflow_run:
    workflows: ["Build GACL"]
    types:
      - completed

jobs:
  test:
    name: Test (${{ matrix.configuration }}-${{ matrix.platform }})
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      checks: write
      contents: read
      actions: read

    strategy:
      fail-fast: false
      matrix:
        configuration: [Debug, Release]
        platform: [x64]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1
          lfs: false

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: gacl-${{ matrix.configuration }}-${{ matrix.platform }}
          path: out
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run native tests
        shell: pwsh
        run: |
          $binDir = "${{ github.workspace }}\out\${{ matrix.configuration }}\${{ matrix.platform }}\bin"
          $testBins = Get-ChildItem -Path $binDir `
            -Filter "*tests.exe" -Recurse
          foreach ($test in $testBins) {
            Push-Location $binDir
            & $test.FullName `
              --gtest_output=xml:"${{ github.workspace }}\TestResults\$($test.BaseName).xml"
            Pop-Location
          }

      - name: Publish test results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Test Results (${{ matrix.configuration }}-${{ matrix.platform }})
          path: TestResults/*.xml
          reporter: java-junit
